controllers/coupons_controller.py
from flask import Blueprint, render_template, request, redirect, session, url_for
from flask_session import Session
from models import Coupon

coupons_controller = Blueprint('coupons_controller', __name__)

@coupons_controller.route("/coupons")
def coupons():
    if 'user_id' not in session:
        return redirect(url_for('login_controller.login'))
    employee_id=session['user_id']
    print(employee_id)
    details = Coupon.query.with_entities(Coupon.coupon_name, Coupon.coupon_code, Coupon.expiry_date).filter_by(user_id=employee_id).all()
    return render_template('coupons.html', title = 'coupons', len = len(details), details=details)

controllers/feed_controller.py
from flask import Blueprint,render_template, redirect, session, url_for
from sqlalchemy.orm import aliased
from sqlalchemy import func
from flask_session import Session
from models import User, Post, Likes,db

feed_controller = Blueprint('feed_controller', __name__)

@feed_controller.route("/feed")
def feed():
    if 'user_id' not in session:
        return redirect(url_for('login_controller.login'))
    manager_alias = aliased(User, name="manager")

    subquery = (
        db.session.query(Likes.post_id)
        .filter(
            Likes.post_id == Post.post_id,
            Likes.user_id == session["user_id"],
        )
        .exists()
    )

    query = (
        db.session.query(
            User.username.label("user_name"),
            manager_alias.username.label("manager_name"),
            func.date_format(Post.timestamp,'%d/%m/%Y').label('timestamp'),
            Post.post_id,
            Post.content,
            Post.category,
            Post.points,
            subquery.label("liked"),
        )
        .join(manager_alias, User.manager_id == manager_alias.user_id)
        .join(Post, User.user_id == Post.user_id)
        .order_by(Post.timestamp.desc())
    )

    result = query.all()
    return render_template('feed.html', posts=result, session = session,len=len(result))

controllers/home_controller.py
from flask import Blueprint, render_template

home_controller = Blueprint('home_controller', __name__)

@home_controller.route("/")
@home_controller.route("/home")
def home():
    return render_template('home.html',title='Home')

controllers/leaderboard_controller.py
from flask import Blueprint,Flask, render_template, redirect, session, url_for, flash, jsonify
from models import User
from flask_session import Session

leaderboard_controller = Blueprint('leaderboard_controller', __name__)

@leaderboard_controller.route("/leaderboard")
def leaderboard():
    if 'user_id' not in session:
        return redirect(url_for('login_controller.login'))
    details = User.query.with_entities(User.username, User.points).order_by(User.points.desc()).all()
    return render_template('leaderboard.html', title = 'leaderboard', len = len(details), details = details)

controllers/login_controller.py
from flask import Blueprint, render_template, request, redirect, session, url_for
from flask_bcrypt import Bcrypt 
from flask_session import Session
from models import User


login_controller = Blueprint('login_controller', __name__)
bcrypt=Bcrypt()
@login_controller.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')

        
        user = User.query.filter_by(username=username).first()
        if user and bcrypt.check_password_hash(user.password, password):
            session['username'] = username
            session['user_id'] = user.user_id
            session['is_manager'] = user.is_manager
            return redirect(url_for('feed_controller.feed'))
        else:
            return render_template('login.html', message='Invalid credentials. Please try again.')

    return render_template('login.html', title = 'Login', message=None)

controllers/manager_controller.py
from flask import Blueprint, render_template, redirect, session, url_for
from sqlalchemy.orm import joinedload
from flask_session import Session
from models import User, Request,db

manager_controller = Blueprint('manager_controller', __name__)

@manager_controller.route("/manager", methods=["GET"])
def manager():
    if "user_id" not in session:
        return redirect(url_for("login_controller.login"))

    if not session.get("is_manager", False):
        return redirect(url_for("feed_controller.feed"))

    manager_user_id = session["user_id"]
    requests = (
        db.session.query(Request)
        .join(User, Request.user_id == User.user_id)
        .filter(User.manager_id == manager_user_id)
        .filter(Request.status == 'pending') 
        .order_by(Request.timestamp.desc())
        .options(joinedload(Request.user))
        .all()
    )

    return render_template("manager.html", requests=requests)

controllers/new_blog_controller.py
from flask import Blueprint, render_template, request, redirect, session, url_for
from flask_bcrypt import Bcrypt 
from flask_session import Session
from models import User, Post,Request,db

new_blog_controller = Blueprint('new_blog_controller', __name__)

@new_blog_controller.route("/new_blog", methods=['GET', 'POST'])
def new_blog():
    if 'user_id' not in session:
        return redirect(url_for('logint_controller.login'))
        
    if not session.get('is_manager', False):
        return redirect(url_for('feed_controller.feed'))

    if request.method == 'POST':

        employee_id = request.form.get('employee_id')
        post_content = request.form.get('post_content')
        category = request.form.get('category')
        points = int(request.form.get('points'))
        print(employee_id)
        print(post_content)
        print(category)
        print(points)

        employee = db.session.get(User, employee_id)
        
        if employee:
            employee.points += points
            employee.curr_points+=points
            db.session.commit()

        request_id = request.form.get('request_id')
        print(request_id)
        if request_id:
            request_to_accept = db.session.query(Request).filter_by(request_id=request_id).first()
            if request_to_accept:
                request_to_accept.status = 'accepted'
                db.session.commit()

        new_post = Post(user_id=employee_id, content=post_content, category=category, points=points)
        db.session.add(new_post)
        db.session.commit()

        return redirect(url_for('feed_controller.feed'))

    else:

        manager_id = session['user_id'] 
        employees = User.query.filter_by(manager_id=manager_id).all()

        user_id = request.args.get('user_id')
        description = request.args.get('description')
        values = request.args.get('values')
        request_id = request.args.get('request_id')
        is_manager_view = request.args.get('is_manager_view')


        employee_choices = [(employee.user_id, f"{employee.name} ({employee.user_id})") for employee in employees]
        return render_template('new_blog.html', title = 'New Post', employee_choices=employee_choices, user_id=user_id, description=description, values=values,
                               is_manager_view=is_manager_view,
                               request_id=request_id)

controllers/profile_controller.py
from flask import Blueprint, render_template, redirect, session, url_for
from flask_session import Session
from models import User, Post, Likes,Request,Coupon,db

profile_controller = Blueprint('profile_controller', __name__)

@profile_controller.route("/Profile", methods=['GET'])
def Profile():
    if 'user_id' not in session:
        return redirect(url_for('login_controller.login'))

    userid = session['user_id'] 
    employees = User.query.filter_by(user_id=userid).first()
    employee_id = employees.user_id
    employee_name=employees.name
    manager=employees.manager_id
    if manager: 
        manager_query = User.query.filter_by(user_id=manager).first()
        employee_manager=manager_query.name
    employee_points = employees.points
    employee_curr_points=employees.curr_points
    if manager: 
        return render_template('profile.html', title = 'New Post', id=employee_id, name=employee_name, manager=employee_manager, points=employee_points, curr_points=employee_curr_points)
    else:
        return render_template('profile.html', title = 'New Post', id=employee_id, name=employee_name, points=employee_points, curr_points=employee_curr_points)

controllers/redeem_points_controller.py
from flask import Blueprint, render_template, request, session ,redirect,url_for
from flask_session import Session
from models import User,Coupon,db
import random
import string


redeem_points_controller = Blueprint('redeem_points_controller', __name__)
def get_random_string(length):
     letters = string.ascii_uppercase
     result_str=''.join(random.choice(letters) for i in range(length))
     return result_str
     
@redeem_points_controller.route('/redeem_points', methods=['GET', 'POST'])
def redeem_points():
    if 'user_id' not in session:
        return redirect(url_for('login_controller.login'))
      
    employee = session['user_id']
    employee_points = User.query.filter_by(user_id=employee).first()

    if employee_points:
        points = employee_points.curr_points
        user_id=employee_points.user_id

        if request.method == 'POST':
            success_messages = []
            error_messages = []
            redeem_option = request.form.get('redeem_option')
            if redeem_option:
                points_key = f"{redeem_option}_points"
                required_points = int(request.form.get(points_key, 0))
                if employee_points.curr_points >= required_points:
                    employee_points.curr_points -= required_points
                    db.session.commit()                   
                    success_messages.append(f'Redeemed {redeem_option.capitalize()} voucher successfully!, {required_points} points deducted.')
                    voucher_name = f"{redeem_option.capitalize()} Voucher"
                    voucher_worth = required_points
                    if required_points==0:
                        return render_template('redeem.html',points=points)                    
                else:
                    error_messages.append(f'Insufficient points to redeem {redeem_option.capitalize()}.')

            if success_messages:
                        s=voucher_name[0]+get_random_string(4)+str(voucher_worth)
                        new_coupon = Coupon(user_id=user_id, coupon_name=voucher_name, coupon_code=s)
                        db.session.add(new_coupon)
                        db.session.commit()
                        return render_template('redeem_success.html', points=employee_points.curr_points, s=s, voucher_name=voucher_name, voucher_worth=voucher_worth)
            elif error_messages:
                        return render_template('redeem_success.html', error_messages=error_messages, points=employee_points.curr_points)
        return render_template('redeem.html', points=points)

controllers/requests_controller.py
from flask import Blueprint, render_template, request, redirect, session, url_for, jsonify
from flask_session import Session
from models import User, Post,Request,db

requests_controller = Blueprint('requests_controller', __name__)

@requests_controller.route('/requests',methods=['POST','GET'])
def request_route():
    if 'user_id' not in session:
        return redirect(url_for('login_controller.login'))
        
    if request.method=='POST':
        description=request.form['Content']
        values=request.form['value']
        new_task=Request(user_id=session["user_id"],description=description,values=values)
        try:
            db.session.add(new_task)
            db.session.commit()
            return redirect(url_for('feed_controller.feed'))
        except Exception as e:
            print(f"Error: {e}")
            return redirect(url_for('feed_controller.feed'))    
    else:
        return render_template('request.html')


@requests_controller.route('/requests/<int:request_id>', methods=['DELETE'])
def reject_request(request_id):
    request_to_reject = Request.query.get(request_id)

    if request_to_reject:
        request_to_reject.status = 'rejected'
        db.session.commit()

        print(f"Request {request_id} Rejected")

        return jsonify({'status': 'success'})
    else:
        return jsonify({'status': 'error', 'message': 'Request not found'}), 404
  

templates/coupons.html
{% extends "layout.html" %} {% block content %}
<section class="bg-coupons">
  <h1 style="color: black; font-size: 5rem; text-align: center">My Coupons</h1>
  <div class="coupons">
    <table class="table table-hover" style="margin-bottom: 0; opacity: 0.8">
      <thead>
        <tr>
          <th scope="col">Sr. No.</th>
          <th scope="col">Coupon Name</th>
          <th scope="col">Coupon Code</th>
          <th scope="col">Expiry Date</th>
        </tr>
      </thead>
      <tbody class="table-group-divider">
        {% for i in range(0, len) %}
        <tr>
          <th scope="row">{{ i + 1 }}</th>
          <td>{{ details[i].coupon_name }}</td>
          <td>{{ details[i].coupon_code}}</td>
          <td>{{ details[i].expiry_date}}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</section>
{% endblock content %}

templates/feed.html
{% extends "layout.html" %} 
{% block content %}
    <div class="outer-content-section">
        {% if len < 1 %}
        <div class="d-flex justify-content-center align-items-center" style="min-height: 70vh;">
            <h1><b>There are no new requests</b></h1>
        </div>
        {% endif %}
        {% for i in range(0, len) %}
        <div class="container mt-5" >
            <div class="card blog-post" id="{{posts[i].post_id}}">
                <!-- Circular Box for Avatar, Manager Name, Employee Name, and Points -->
                <div class="avatar-box">
                    <div class="avatar-info">
                        <img src="/static/img/profile.png" alt="M" class="avatar" style="margin-right: 2%">
                        &ensp;
                        <div><b>{{posts[i].user_name}}</b></div>
                    </div>
                    <div><b>Date:</b> {{posts[i].timestamp}}</div>
                </div>
                <!-- Employee Name and Points -->
                <div class="employee-points">
                    <div><i>Appreciated By</i> <b>{{posts[i].manager_name}}</b></div>
                    <div><b>Points:</b> <span id="{{posts[i].post_id}}points">{{posts[i].points}}</span></div>
                </div>
    
                <!-- Content Box with Values and V1, V2 Sub-boxes -->
                <div class="content-box">
                    <!-- Variable Content Goes Here -->
                    <p>{{posts[i].content}}</p>
                    <!-- End Variable Content -->
                </div>
                <div class="v-box">
                    
                    <button 
                    {%if posts[i].liked==True%}
                    class="btn btn-light v-sub-box liked" onclick="unliked('{{posts[i].post_id}}')"
                    {%else%}
                    class="btn btn-light v-sub-box unliked" onclick="liked('{{posts[i].post_id}}')" 
                    {%endif%}
                    id='{{posts[i].post_id}}button' style="border: var(--bs-card-border-width) solid var(--bs-card-border-color);">
                    
                        <i class="fa fa-heart"></i>
                    </button>
                    <button type="button" class="btn btn-light v-sub-box" style="margin-right: 0;">{{ posts[i].category }}</button>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock content %}

templates/leaderboard.html
{% extends "layout.html" %}
{% block content %}
  <section class="bg-leaderboard">
    <h1 style="color: black; font-size: 5rem; text-align: center;"><strong>Leaderboard</strong></h1>
    <div class = 'leaderboard'>
      <table class="table table-hover" style="margin-bottom: 0; opacity: 0.8;">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Username</th>
            <th scope="col">Points</th>
          </tr>
        </thead>
        <tbody class="table-group-divider">
          {% for i in range(0, len) %}
            <tr>
                <th scope="row">{{ i + 1 }}</th>
                <td>{{ details[i].username }}</td>
                <td>{{ details[i].points }}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </section>
{% endblock content %}

templates/manager.html
{% extends 'layout.html' %}
{% block content %}


<div class="manager-main">
    <div class="manager">
        {% if requests|length < 1 %}
        <div class="d-flex justify-content-center align-items-center" style="min-height: 70vh;">
            <h1><b>There are no new requests</b></h1>
        </div>
        {% endif %}

        {% for request in requests %}
        <div class="box" data-post-id="{{ request.request_id }}">
            <div class="user-info">
                <h4 style="font-family: 'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif;">
                    <b>Requested By: {{ request.user.name }}</b>
                </h4>
            </div>
            <div class="content-container">
                <h5><b>Description</b></h5>
                <div class="description">
                    {{ request.description }}
                </div>
                <div class="value-info">
                    <h5 style="font-family: 'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif;">Value: {{ request.values }}</h5>
                </div>
            </div>
            <!-- Accept and Decline buttons -->
            <div class="buttons">
                <a href="{{ url_for('new_blog_controller.new_blog', user_id=request.user_id, description=request.description, values=request.values, request_id=request.request_id, is_manager_view=true) }}">
                    <button class="acceptBtn btn btn-dark">Accept</button>
                </a>
                <button class="declineBtn btn btn-dark">Decline</button>
            </div>               
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/new_blog.html
{% extends "layout.html" %}
{% block content %}
<section class="custom-styles">
    <div class="content-section">
        <h2 class="article-title"><strong>Create a New Post</strong></h2>

        <form action="{{ url_for('new_blog_controller.new_blog') }}" method="post" id="postForm">
            {% if request_id %}
                <input type="hidden" name="request_id" value="{{ request_id }}">
            {% endif %}
            <div class="form-group">
                <label for="employee_id">Select Employee:</label>
                <select id="employee_id" name="employee_id" class="form-control" required {% if is_manager_view %} disabled {% endif %}>
                    {% for emp_id, name in employee_choices %}
                        <option value="{{ emp_id }}">{{ name }}</option>
                    {% endfor %}
                </select>
            </div>

            <div class="form-group">
                <label for="post_content">Description:</label>
                <textarea id="post_content" name="post_content" class="form-control" rows="3">{{ description or '' }}</textarea>
            </div>

            <div class="form-group">
                <label style="margin-right: 0.5rem;">Values:</label>
                {% for category in ['Innovation', 'Integrity', 'Ambition', 'Teamwork'] %}
                    <div class="form-check form-check-inline">
                        <input type="radio" id="{{ category.lower() }}" name="category" value="{{ category }}" class="form-check-input" {% if values and category.lower() == values.lower() %} checked {% endif %} {% if is_manager_view %} disabled {% endif %} required>
                        <label for="{{ category.lower() }}" class="form-check-label">{{ category }}</label>
                    </div>
                {% endfor %}
            </div>

            <div class="form-group">
                <label for="points">Points:</label>
                <select id="points" name="points" class="form-control" required>
                    <option value="50">50</option>
                    <option value="100">100</option>
                    <option value="150">150</option>
                    <option value="200">200</option>
                    <option value="300">300</option>
                </select>
            </div>

            <div class="form-group">
                <button type="button" onclick="enableFieldsAndSubmit()" class="btn btn-primary btn-dark">Create Post</button>
            </div>
        </form>
    </div>
</section>

<script>
    document.getElementById("employee_id").value = "{{ user_id }}";

    function enableFieldsAndSubmit() {
        var postContent = document.getElementById("post_content").value.trim();
        var description = "{{ description }}".trim();
        if (postContent === description) {
            alert("Post content must be different from the description. Please modify it.");
            return;
        }
        document.getElementById("employee_id").disabled = false;

        var radioButtons = document.getElementsByName("category");
        for (var i = 0; i < radioButtons.length; i++) {
            radioButtons[i].disabled = false;
        }
        
        document.getElementById("postForm").submit();
    }
</script>

{% endblock %}

templates/redeem.html
{% extends "layout.html" %} {% block content %}
<style>
  img {
    display: block;
    margin-bottom: 5px;
  }

  label {
    display: block;
    margin-bottom: 5px;
  }
</style>
<div class="redeem-styles">
  <div class="content-section">
    <h2>Redeem Your {{points}} Points</h2>
    <form action="{{ url_for('redeem_points_controller.redeem_points') }}" method="post">
      <div class="form-group">
        <div class="form-check form-check-inline">
          <img
            src="/static/img/zomato.png"
            alt=""
            width="290px"
            height="130px"
            onclick="updateDropdownEnabled('zomato', `{{ points }}`)"
          />
          <label for="zomato">Zomato Gift Card</label>
          <input
            type="radio"
            name="redeem_option"
            value="zomato"
            id="zomato_enabled"
            onclick="updateDropdownEnabled('zomato', `{{ points }}`)"
          />
          <select name="zomato_points" id="zomato_points" disabled>
            <option value="0">--Select from below options--</option>
            <option value="50">Get 50/- off using 50 points</option>
            <option value="100">Get 100/- off using 100 points</option>
            <option value="200">Get 200/- off using 200 points</option>
            <option value="500">Get 500/- off using 500 points</option>
          </select>
        </div>

        <div class="form-check form-check-inline">
          <img
            src="/static/img/amazon.png"
            alt=""
            width="290px"
            height="130px"
            onclick="updateDropdownEnabled('amazon', `{{ points }}`)"
          />
          <label for="amazon">Amazon Gift Card</label>
          <input
            type="radio"
            name="redeem_option"
            value="amazon"
            id="amazon_enabled"
            onclick="updateDropdownEnabled('amazon', `{{ points }}`)"
          />
          <select name="amazon_points" id="amazon_points" disabled>
            <option value="0">--Select from below options--</option>
            <option value="100">Get 100/- off using 100 points</option>
            <option value="500">Get 500/- off using 500 points</option>
            <option value="800">Get 800/- off using 800 points</option>
          </select>
        </div>

        <div class="form-check form-check-inline">
          <img
            src="/static/img/MMT.png"
            alt=""
            width="290px"
            height="130px"
            onclick="updateDropdownEnabled('MakeMyTrip', `{{ points }}`)"
          />
          <label for="mmt">MakeMyTrip Voucher</label>
          <input
            type="radio"
            name="redeem_option"
            value="MakeMyTrip"
            id="MakeMyTrip_enabled"
            onclick="updateDropdownEnabled('MakeMyTrip', `{{ points }}`)"
          />
          <select name="MakeMyTrip_points" id="MakeMyTrip_points" disabled>
            <option value="0">--Select from below options--</option>
            <option value="500">Get 500/- off using 500 points</option>
            <option value="750">Get 750/- off using 750 points</option>
            <option value="1000">Get 1000/- off using 1000 points</option>
          </select>
        </div>

        <div class="form-check form-check-inline">
          <img
            src="/static/img/dominos.png"
            alt=""
            width="290px"
            height="130px"
            onclick="updateDropdownEnabled('Dominos', `{{ points }}`)"
          />
          <label for="Dominos">Dominos Gift Card</label>
          <input
            type="radio"
            name="redeem_option"
            value="Dominos"
            id="Dominos_enabled"
            onclick="updateDropdownEnabled('Dominos', `{{ points }}`)"
          />
          <select name="Dominos_points" id="Dominos_points" disabled>
            <option value="0">--Select from below options--</option>
            <option value="50">Get 50/- off using 50 points</option>
            <option value="100">Get 100/- off using 100 points</option>
            <option value="200">Get 200/- off using 200 points</option>
            <option value="500">Get 500/- off using 500 points</option>
          </select>
        </div>

        <div class="form-check form-check-inline">
          <img
            src="/static/img/Bata.png"
            alt=""
            width="290px"
            height="130px"
            onclick="updateDropdownEnabled('Bata', `{{ points }}`)"
          />
          <label for="Bata">Bata Gift Card</label>
          <input
            type="radio"
            name="redeem_option"
            value="Bata"
            id="Bata_enabled"
            onclick="updateDropdownEnabled('Bata', `{{ points }}`)"
          />
          <select name="Bata_points" id="Bata_points" disabled>
            <option value="0">--Select from below options--</option>
            <option value="100">Get 100/- off using 100 points</option>
            <option value="500">Get 500/- off using 500 points</option>
            <option value="800">Get 800/- off using 800 points</option>
          </select>
        </div>

        <div class="form-check form-check-inline">
          <img
            src="/static/img/croma.png"
            alt=""
            width="290px"
            height="130px"
            onclick="updateDropdownEnabled('Croma', `{{ points }}`)"
          />
          <label for="Croma">Croma Gift Card</label>
          <input
            type="radio"
            name="redeem_option"
            value="Croma"
            id="Croma_enabled"
            onclick="updateDropdownEnabled('Croma', `{{ points }}`)"
          />
          <select name="Croma_points" id="Croma_points" disabled>
            <option value="0">--Select from below options--</option>
            <option value="500">Get 500/- off using 500 points</option>
            <option value="750">Get 750/- off using 750 points</option>
            <option value="1000">Get 1000/- off using 1000 points</option>
          </select>
        </div>

        <div class="form-check form-check-inline">
          <img
            src="/static/img/Prestige.png"
            alt=""
            width="290px"
            height="130px"
            onclick="updateDropdownEnabled('Prestige', `{{ points }}`)"
          />
          <label for="Prestige">Prestige Gift Card</label>
          <input
            type="radio"
            name="redeem_option"
            value="Prestige"
            id="Prestige_enabled"
            onclick="updateDropdownEnabled('Prestige', `{{ points }}`)"
          />
          <select name="Prestige_points" id="Prestige_points" disabled>
            <option value="0">--Select from below options--</option>
            <option value="100">Get 100/- off using 100 points</option>
            <option value="500">Get 500/- off using 500 points</option>
            <option value="800">Get 800/- off using 800 points</option>
          </select>
        </div>

        <div class="form-check form-check-inline">
          <img
            src="/static/img/Swiggy.png"
            alt=""
            width="290px"
            height="130px"
            onclick="updateDropdownEnabled('Swiggy', `{{ points }}`)"
          />
          <label for="Swiggy">Swiggy Gift Card</label>
          <input
            type="radio"
            name="redeem_option"
            value="Swiggy"
            id="Swiggy_enabled"
            onclick="updateDropdownEnabled('Swiggy', `{{ points }}`)"
          />
          <select name="Swiggy_points" id="Swiggy_points" disabled>
            <option value="0">--Select from below options--</option>
            <option value="50">Get 50/- off using 50 points</option>
            <option value="100">Get 100/- off using 100 points</option>
            <option value="200">Get 200/- off using 200 points</option>
            <option value="500">Get 500/- off using 500 points</option>
          </select>
        </div>

        <div class="form-check form-check-inline">
          <img
            src="/static/img/netmeds.png"
            alt=""
            width="290px"
            height="130px"
            onclick="updateDropdownEnabled('Netmeds', `{{ points }}`)"
          />
          <label for="Netmeds">Netmeds Gift Card</label>
          <input
            type="radio"
            name="redeem_option"
            value="Netmeds"
            id="Netmeds_enabled"
            onclick="updateDropdownEnabled('Netmeds', `{{ points }}`)"
          />
          <select name="Netmeds_points" id="Netmeds_points" disabled>
            <option value="0">--Select from below options--</option>
            <option value="100">Get 100/- off using 100 points</option>
            <option value="500">Get 500/- off using 500 points</option>
            <option value="750">Get 750/- off using 750 points</option>
            <option value="1000">Get 1000/- off using 1000 points</option>
          </select>
        </div>
      </div>

      <div class="form-group" align="center">
        <button type="submit" class="btn btn-dark">Redeem Points</button>
      </div>
    </form>
  </div>
</div>
<script>
  function updateDropdownEnabled(option, userPoints) {
    var r_button = document.getElementById(option + "_enabled");
    r_button.checked = true;
    var pointsDropdown = document.getElementById(option + "_points");
    var options = pointsDropdown.options;
    pointsDropdown.disabled = false;
    for (var i = 0; i < options.length; i++) {
      options[i].style.display =
        parseInt(options[i].value) <= userPoints ? "block" : "none";
    }
  }
</script>

{% endblock %}